version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: latencylens_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: latencylens
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: latencylens
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
